version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/finsim

    steps:
      - checkout

      - run:
          name: Installing Packages
          command: |
            pip install --upgrade --user pip
            pip install --upgrade --user .
            pip install --upgrade --user pytest

      - run:
          name: Run Unit Tests
          command: |
            pytest
