version: 2

shared: &shared
  working_directory: ~/finsim

  resource_class: medium+
  steps:
    - checkout

    - run:
        name: Apt Install
        command: |
          sudo apt-get update
          sudo apt-get install -y libc6

    - run:
        name: Installing Packages
        command: |
          pip install --upgrade --user pip
          pip install --upgrade --user .

    - run:
        name: Run Unit Tests
        command: |
          pip install --upgrade --user .[test]
          pytest



jobs:
  py310:
    <<: *shared
    docker:
      - image: cimg/python:3.10

  py311:
    <<: *shared
    docker:
      - image: cimg/python:3.11

  py312:
    <<: *shared
    docker:
      - image: cimg/python:3.12

  py313:
    <<: *shared
    docker:
      - image: cimg/python:3.13

workflows:
  version: 2
  build:
    jobs:
      - py310
      - py311
      - py312
      - py313
