name: Python package CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --user --upgrade pip
          pip install --user --upgrade setuptools wheel Cython
          pip cache purge
          pip install --user .
          pip install --user .[test]
      - name: Run tests
        run: pytest --doctest-cython
